default: &default
  adapter: 'postgresql'
  database: 'wanderlust_main_db'

development:
  <<: *default
  database: 'wanderlust_main_db'

test:
  <<: *default
  database: 'wanderlust_main_db'

production:
  <<: *default
  database: 'wanderlust_main_db'