default: &default
  adapter: 'postgresql'
  database: 'wanderlust_database'

development:
  <<: *default
  database: 'wanderlust_database'

test:
  <<: *default
  database: 'wanderlust_database'

production:
  <<: *default
  database: 'wanderlust_database'
